use super::{std_function, StdArity, StdFunction, StdFunctionKind, StdModule, StdType};
use crate::stdlib::std_module;

const INTRINSIC_FUNCTIONS: &[StdFunction] = &[
    // Conversion (internal only)
    std_function(
        "to_string",
        StdFunctionKind::UtilToString,
        StdArity::Exact(1),
        &[StdType::Any],
        StdType::String,
    ),
    // String utilities
    std_function(
        "string_index_of",
        StdFunctionKind::StringIndexOf,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::Int,
    ),
    std_function(
        "string_split",
        StdFunctionKind::StringSplit,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::List,
    ),
    std_function(
        "string_contains",
        StdFunctionKind::StringContains,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::Bool,
    ),
    std_function(
        "string_replace",
        StdFunctionKind::StringReplace,
        StdArity::Exact(3),
        &[StdType::String, StdType::String, StdType::String],
        StdType::String,
    ),
    std_function(
        "string_to_lower",
        StdFunctionKind::StringToLower,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "string_to_upper",
        StdFunctionKind::StringToUpper,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    // Math
    std_function(
        "math_floor",
        StdFunctionKind::MathFloor,
        StdArity::Exact(1),
        &[StdType::Float],
        StdType::Int,
    ),
    std_function(
        "math_ceil",
        StdFunctionKind::MathCeil,
        StdArity::Exact(1),
        &[StdType::Float],
        StdType::Int,
    ),
    std_function(
        "math_round",
        StdFunctionKind::MathRound,
        StdArity::Exact(1),
        &[StdType::Float],
        StdType::Int,
    ),
    std_function(
        "math_abs",
        StdFunctionKind::MathAbs,
        StdArity::Exact(1),
        &[StdType::Float],
        StdType::Float,
    ),
    std_function(
        "math_sqrt",
        StdFunctionKind::MathSqrt,
        StdArity::Exact(1),
        &[StdType::Float],
        StdType::Float,
    ),
    std_function(
        "math_min",
        StdFunctionKind::MathMin,
        StdArity::Exact(2),
        &[StdType::Float, StdType::Float],
        StdType::Float,
    ),
    std_function(
        "math_max",
        StdFunctionKind::MathMax,
        StdArity::Exact(2),
        &[StdType::Float, StdType::Float],
        StdType::Float,
    ),
    // Assertions
    std_function(
        "fail",
        StdFunctionKind::AssertFail,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Void,
    ),
    // Environment
    std_function(
        "env_get",
        StdFunctionKind::EnvGet,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "env_get_or",
        StdFunctionKind::EnvGetOr,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::String,
    ),
    std_function(
        "env_has",
        StdFunctionKind::EnvHas,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Bool,
    ),
    std_function(
        "env_require",
        StdFunctionKind::EnvRequire,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "env_set",
        StdFunctionKind::EnvSet,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::Void,
    ),
    std_function(
        "env_unset",
        StdFunctionKind::EnvUnset,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Void,
    ),
    std_function(
        "env_vars",
        StdFunctionKind::EnvVars,
        StdArity::Exact(0),
        &[],
        StdType::Dict,
    ),
    std_function(
        "env_cwd",
        StdFunctionKind::EnvCwd,
        StdArity::Exact(0),
        &[],
        StdType::String,
    ),
    std_function(
        "env_set_cwd",
        StdFunctionKind::EnvSetCwd,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Void,
    ),
    std_function(
        "env_temp_dir",
        StdFunctionKind::EnvTempDir,
        StdArity::Exact(0),
        &[],
        StdType::String,
    ),
    std_function(
        "env_home_dir",
        StdFunctionKind::EnvHomeDir,
        StdArity::Exact(0),
        &[],
        StdType::String,
    ),
    std_function(
        "env_config_dir",
        StdFunctionKind::EnvConfigDir,
        StdArity::Exact(0),
        &[],
        StdType::String,
    ),
    // Filesystem
    std_function(
        "fs_read_text",
        StdFunctionKind::FsReadText,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "fs_read_bytes",
        StdFunctionKind::FsReadBytes,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::List,
    ),
    std_function(
        "fs_write_text",
        StdFunctionKind::FsWriteText,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::Void,
    ),
    std_function(
        "fs_write_bytes",
        StdFunctionKind::FsWriteBytes,
        StdArity::Exact(2),
        &[StdType::String, StdType::List],
        StdType::Void,
    ),
    std_function(
        "fs_write_bytes_atomic",
        StdFunctionKind::FsWriteBytesAtomic,
        StdArity::Exact(2),
        &[StdType::String, StdType::List],
        StdType::Void,
    ),
    std_function(
        "fs_create_dir",
        StdFunctionKind::FsCreateDir,
        StdArity::Range {
            min: 1,
            max: Some(2),
        },
        &[StdType::String, StdType::Bool],
        StdType::Void,
    ),
    std_function(
        "fs_ensure_dir",
        StdFunctionKind::FsEnsureDir,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Void,
    ),
    std_function(
        "fs_remove",
        StdFunctionKind::FsRemove,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Void,
    ),
    std_function(
        "fs_exists",
        StdFunctionKind::FsExists,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Bool,
    ),
    std_function(
        "fs_list_dir",
        StdFunctionKind::FsListDir,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::List,
    ),
    std_function(
        "fs_walk",
        StdFunctionKind::FsWalk,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::List,
    ),
    std_function(
        "fs_glob",
        StdFunctionKind::FsGlob,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::List,
    ),
    std_function(
        "fs_copy",
        StdFunctionKind::FsCopy,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::Void,
    ),
    std_function(
        "fs_rename",
        StdFunctionKind::FsRename,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::Void,
    ),
    std_function(
        "fs_stat",
        StdFunctionKind::FsStat,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Dict,
    ),
    // Path
    std_function(
        "path_join",
        StdFunctionKind::PathJoin,
        StdArity::Exact(1),
        &[StdType::List],
        StdType::String,
    ),
    std_function(
        "path_components",
        StdFunctionKind::PathComponents,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::List,
    ),
    std_function(
        "path_dirname",
        StdFunctionKind::PathDirname,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "path_basename",
        StdFunctionKind::PathBasename,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "path_extension",
        StdFunctionKind::PathExtension,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "path_normalize",
        StdFunctionKind::PathNormalize,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "path_absolute",
        StdFunctionKind::PathAbsolute,
        StdArity::Range {
            min: 1,
            max: Some(2),
        },
        &[StdType::String, StdType::String],
        StdType::String,
    ),
    std_function(
        "path_relative",
        StdFunctionKind::PathRelative,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::String,
    ),
    std_function(
        "path_is_absolute",
        StdFunctionKind::PathIsAbsolute,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Bool,
    ),
    std_function(
        "path_separator",
        StdFunctionKind::PathSeparator,
        StdArity::Exact(0),
        &[],
        StdType::String,
    ),
    // URL
    std_function(
        "url_encode_component",
        StdFunctionKind::UrlEncodeComponent,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "url_decode_component",
        StdFunctionKind::UrlDecodeComponent,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::String,
    ),
    std_function(
        "url_build_query",
        StdFunctionKind::UrlBuildQuery,
        StdArity::Exact(1),
        &[StdType::Dict],
        StdType::String,
    ),
    std_function(
        "url_append_query",
        StdFunctionKind::UrlAppendQuery,
        StdArity::Exact(2),
        &[StdType::String, StdType::Dict],
        StdType::String,
    ),
    std_function(
        "url_join",
        StdFunctionKind::UrlJoin,
        StdArity::Exact(2),
        &[StdType::String, StdType::String],
        StdType::String,
    ),
    // Time
    std_function(
        "time_now_unix_millis",
        StdFunctionKind::TimeNowUnixMillis,
        StdArity::Exact(0),
        &[],
        StdType::Int,
    ),
    std_function(
        "time_unix_seconds",
        StdFunctionKind::TimeUnixSeconds,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::Int,
    ),
    std_function(
        "time_sleep_ms",
        StdFunctionKind::TimeSleepMs,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::Void,
    ),
    std_function(
        "time_format_rfc3339",
        StdFunctionKind::TimeFormatRfc3339,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::String,
    ),
    std_function(
        "time_parse_rfc3339",
        StdFunctionKind::TimeParseRfc3339,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Dict,
    ),
    // Process execution
    std_function(
        "process_run",
        StdFunctionKind::ProcessRun,
        StdArity::Range {
            min: 1,
            max: Some(5),
        },
        &[
            StdType::String,
            StdType::List,
            StdType::Dict,
            StdType::String,
            StdType::String,
        ],
        StdType::Struct,
    ),
    std_function(
        "process_spawn",
        StdFunctionKind::ProcessSpawn,
        StdArity::Range {
            min: 1,
            max: Some(4),
        },
        &[
            StdType::String,
            StdType::List,
            StdType::Dict,
            StdType::String,
        ],
        StdType::Int,
    ),
    std_function(
        "process_wait",
        StdFunctionKind::ProcessWait,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::Struct,
    ),
    std_function(
        "process_kill",
        StdFunctionKind::ProcessKill,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::Bool,
    ),
    std_function(
        "process_read_stdout",
        StdFunctionKind::ProcessReadStdout,
        StdArity::Range {
            min: 1,
            max: Some(2),
        },
        &[StdType::Int, StdType::Int],
        StdType::String,
    ),
    std_function(
        "process_read_stderr",
        StdFunctionKind::ProcessReadStderr,
        StdArity::Range {
            min: 1,
            max: Some(2),
        },
        &[StdType::Int, StdType::Int],
        StdType::String,
    ),
    std_function(
        "process_write_stdin",
        StdFunctionKind::ProcessWriteStdin,
        StdArity::Exact(2),
        &[StdType::Int, StdType::String],
        StdType::Void,
    ),
    std_function(
        "process_close_stdin",
        StdFunctionKind::ProcessCloseStdin,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::Void,
    ),
    std_function(
        "process_close",
        StdFunctionKind::ProcessClose,
        StdArity::Exact(1),
        &[StdType::Int],
        StdType::Void,
    ),
    // Args intrinsics
    std_function(
        "args_all",
        StdFunctionKind::ArgsAll,
        StdArity::Exact(0),
        &[],
        StdType::List,
    ),
    std_function(
        "args_program",
        StdFunctionKind::ArgsProgram,
        StdArity::Exact(0),
        &[],
        StdType::String,
    ),
    std_function(
        "cli_parse",
        StdFunctionKind::CliParse,
        StdArity::Range {
            min: 1,
            max: Some(2),
        },
        &[StdType::Any, StdType::List],
        StdType::Struct,
    ),
    // Regex intrinsics
    std_function(
        "regex_compile",
        StdFunctionKind::RegexCompile,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Int,
    ),
    std_function(
        "regex_is_match",
        StdFunctionKind::RegexIsMatch,
        StdArity::Exact(2),
        &[StdType::Int, StdType::String],
        StdType::Bool,
    ),
    std_function(
        "regex_find_all",
        StdFunctionKind::RegexFindAll,
        StdArity::Exact(2),
        &[StdType::Int, StdType::String],
        StdType::List,
    ),
    std_function(
        "regex_captures",
        StdFunctionKind::RegexCaptures,
        StdArity::Exact(2),
        &[StdType::Int, StdType::String],
        StdType::List,
    ),
    std_function(
        "regex_replace",
        StdFunctionKind::RegexReplace,
        StdArity::Exact(3),
        &[StdType::Int, StdType::String, StdType::String],
        StdType::String,
    ),
    std_function(
        "regex_replace_all",
        StdFunctionKind::RegexReplaceAll,
        StdArity::Exact(3),
        &[StdType::Int, StdType::String, StdType::String],
        StdType::String,
    ),
    std_function(
        "regex_split",
        StdFunctionKind::RegexSplit,
        StdArity::Exact(2),
        &[StdType::Int, StdType::String],
        StdType::List,
    ),
    // JSON encoding/decoding
    std_function(
        "json_encode",
        StdFunctionKind::JsonEncode,
        StdArity::Exact(1),
        &[StdType::Any],
        StdType::String,
    ),
    std_function(
        "json_decode",
        StdFunctionKind::JsonDecode,
        StdArity::Exact(1),
        &[StdType::String],
        StdType::Any,
    ),
    // HTTP
    std_function(
        "http_send",
        StdFunctionKind::HttpSend,
        StdArity::Exact(5),
        &[
            StdType::String,
            StdType::String,
            StdType::Dict,
            StdType::String,
            StdType::Int,
        ],
        StdType::Dict,
    ),
];

pub const MODULE: StdModule = std_module!(
    "std.intrinsics",
    "Low-level intrinsic functions that provide native functionality",
    INTRINSIC_FUNCTIONS
);
