; AUTO-GENERATED from docs/tokens.toml
; Do not edit this file directly - run `npm run codegen` to regenerate

; Keywords
[
  "def"
  "pub"
  "var"
  "const"
  "use"
  "struct"
  "enum"
  "if"
  "else"
  "unless"
  "while"
  "until"
  "return"
  "test"
  "end"
] @keyword

(error_definition
  "error" @keyword)

(throw_statement
  "throw" @keyword)

(try_expression
  "try" @keyword)

(catch_clause
  "catch" @keyword)

(match_case_block
  "case" @keyword)

(match_case_expression
  "case" @keyword)

(catch_case
  "case" @keyword)

(function_definition
  name: (identifier) @function)

(function_definition
  return_type: (_) @type)

(error_type
  name: (identifier) @type)

(error_type
  variant: (identifier) @constructor)

(struct_definition
  name: (identifier) @type)

(enum_definition
  name: (identifier) @type)

(error_definition
  name: (identifier) @type)

(error_variant
  name: (identifier) @constructor)

(error_field
  name: (identifier) @property)

(parameter
  name: (identifier) @variable.parameter)

(parameter
  type: (_) @type)

(type_annotation
  (identifier) @type)

(call_expression
  function: (identifier) @function.call)

(member_expression
  property: (identifier) @property)

(var_declaration
  name: (identifier) @variable)

(const_declaration
  name: (identifier) @constant)

(use_statement
  alias: (identifier) @namespace)

(catch_clause
  binding: (identifier) @variable)

[
  (string)
  (template_string)
] @string

(number) @number

(boolean) @boolean

(nil) @constant.builtin

(comment) @comment
