name: PR Checks

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      LLVM_SYS_170_PREFIX: /usr/lib/llvm-17
      LLVM_CONFIG_PATH: /usr/lib/llvm-17/bin/llvm-config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-17-dev libpolly-17-dev

      - name: Cache cargo builds
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run workspace tests
        run: cargo test --workspace --exclude tea-cli

      - name: Run tea test harness
        run: cargo run -p tea-cli -- test --fail-fast

      - name: Run e2e sanity checks
        run: scripts/e2e.sh
